### ISSUE TITLE
Class 'MaterializeCSS' not found

### ISSUE THREAD

**Issue by schystz** [skydiver/laravel-materialize-css#2]
Hi, I followed your instruction and has successfully installed the library. However, when I try to use it inside the blade file, I get a fatal error `Class 'MaterializeCSS' not found`. I already added the MaterializeCSSServiceProvider in config/app.php, what else am I missing? TIA!

**Comment by juaniyyo** [comment]
I have the same problem. Help please

**Comment by skydiver** [comment]
Please, add the facade to aliases array on config/app.php:

``` php
    'MaterializeCSS' => 'Skydiver\LaravelMaterializeCSS\MaterializeCSS',
```

Don't know why this was missing.

I've added to the documentation.

Sorry for the trouble and thanks.

**Comment by myohanhtet** [comment]
I have same problem.Already  added aliases array but is not ok.In laravel 5.3
