### ISSUE TITLE
Call to undefined method Illuminate\Foundation\Application::bindShared()

### ISSUE THREAD

**Issue by romarioliveira25** [skydiver/laravel-materialize-css#4]
Hi,

Through the version 5.2.5 of Laravel framework, I had a compatibility issue related with the method bindShared() in the Illuminate HTML. Searching a bit about, I found a issue repported about in :(https://github.com/illuminate/html/pull/31/files), where the solution recommended is change the method bindShared() to singleton() at the service provider php file(HtmlServiceProvider.php). 

So, in resuming, I had the same issue to install the MaterializeCSS package, and to solve it (apparently), I have done the same change at the service provider php file (MaterializeCSSServiceProvider.php).

Well, sorry if it's not sounds like a glue for it (I'm starting with Laravel :-P), anyway I hope this helps :-)

**Comment by skydiver** [comment]
Hey, great catch!

Thanks.-

**Comment by romarioliveira25** [comment]
Haha, for nothing. :+1: 

I stay happy to can help!
